apiVersion: v1
kind: Secret
metadata:
  name: private-repo-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/JudetheGemini/DevOps-Coding-Assessment.git
  username: JudetheGemini
  password: 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
  type: git
  # password: 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
