apiVersion: v1
kind: Secret
metadata:
  name: private-repo-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/JudetheGemini/DevOps-Coding-Assessment.git
  username: JudetheGemini
  # password: 
  type: git
